services:
  app:
      image: patientor-frontend
      build:
        context: . # The context will pick this directory as the "build context"
        dockerfile: frontend/dev.Dockerfile # This will simply tell which dockerfile to read
      volumes:
        - ./frontend/:/usr/src/patientor/frontend # The path can be relative, so ./ is enough to say "the same location as the docker-compose.yml"
      ports:
        - 3210:3000
      container_name: patientor-frontend # This will name the container patientor-frontend
  server:                    # The name of the service, can be anything
    image: patientor-backend    # Declares which image to use
    build:
      context: . # The context will pick this directory as the "build context"
      dockerfile: backend/dev.Dockerfile # This will simply tell which dockerfile to read
    volumes:
      - ./backend:/usr/src/patientor/backend # The path can be relative, so ./ is enough to say "the same location as the docker-compose.yml"
    ports:
      - 3001:3001
    container_name: patientor-backend # This will name the container patientor-backend